name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv & project, then add ruff, pytest, pytest-cov into venv
        run: |
          pip install uv
          make install
          uv run pip install ruff pytest pytest-cov

      - name: Run lint and tests
        run: make check

      - name: Run test coverage
        run: make coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
        with:
          args: >
            -Dsonar.organization=RomanVetrov
            -Dsonar.projectKey=RomanVetrov_python-project-50
            -Dsonar.python.coverage.reportPaths=coverage.xml

