name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv & project, then add ruff into venv
        run: |
          pip install uv
          make install
          uv run pip install ruff pytest pytest-cov

      - name: Run lint and tests
        run: |
          make check

      - name: Run test coverage
        run: |
          make coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: ${{ secrets.SONAR_ORGANIZATION }}
          projectKey:   ${{ secrets.SONAR_PROJECT_KEY }}
          token:        ${{ secrets.SONAR_TOKEN }}
