name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: pip install -e .[dev]

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: ${{ secrets.SONAR_ORGANIZATION }}
          projectKey:    ${{ secrets.SONAR_PROJECT_KEY }}
          token:         ${{ secrets.SONAR_TOKEN }}








